### PR TITLE
Various Bugfixes for ARM

### LINKED ISSUE #988: 🐛 Adding a new drive to ARM and forgetting to rescan drives fails harder than it should
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

If you have ARM running, shut it down, add a drive (say, you finally found that extra USB-connected drive to add to your ripping machine), then start ARM up again you MUST rescan the drives from the "ARM Settings"/General info page.

If you don't, inserting a disk into the new drive will result in silent failure. The log file will be empty, and there will be a job you can't abandon and may not be able to delete from the database page. Entering the docker container with `docker exec -it arm-rippers bash` and then running `.../ripper/main.py` directly shows an `AttributeError` on `NoneType` stack trace.

### To Reproduce

1. Have a drive you can add and remove (e.g. a USB-connected external drive)
2. Start ARM initially with the drive not present.
3. Verify on the ARM "System Info" page that the drive does not exist.
4. Attach drive
5. Put something into drive.

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

A.R.M version: 2.6.67

### Expected behavior?

Basically, not break this hard when an unexpected new device shows up.

My initial suggestion would be that `arm/ripper/main.py` should check whether the device it's handed as the `-d` argument exists in the `system_drives` table and, if not, immediately eject the disc and send a notification with `arm.ripper.utils.notify` that the drive is not known and the user should go to the "ARM Settings" page and rescan available drives.

Beyond that, all uses of `SystemDrives.query.filter_by` should be defensively coded to allow for the possibility that the return is `None`, and beyond *that* there should be some `try`...`finally` logic inside `arm/ripper/main.py` so that slamming into an unexpected exception can't leave you in a state with a job in the database that can't be abandoned or deleted - if `arm/ripper/main.py` is able to write to the database at all when the process exits, there shouldn't be a job entry in the database marked as active after the associated process exits.

### Relevant log output

```shell
"docker logs" shows this when trying to delete the DB entry:

[2023-11-27 02:40:44,384] DEBUG ARM: json_api.delete_job job_id= 28
[2023-11-27 02:40:44,385] DEBUG ARM: json_api.delete_job Admin requesting delete job 28 from database!
[2023-11-27 02:40:44,385] DEBUG ARM: json_api.delete_job No errors: job_id=28
[2023-11-27 02:40:44,387] ERROR ARM: json_api.delete_job Error:db-1 'NoneType' object has no attribute 'job_id_previous'


Attempting to run "arm/ripper/main.py" at the command line you get from "docker exec -it arm-rippers bash" produces this:

root@548aea4dc3be:/home/arm# /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr1
[2023-11-27 02:44:11,838] DEBUG ARM: __init__.<module> Debugging pin: 12345
[2023-11-27 02:44:12,226] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 469d88477c13
[2023-11-27 02:44:12,262] DEBUG ARM: utils.arm_db_get Database Head is: 469d88477c13
[2023-11-27 02:44:12,263] DEBUG ARM: utils.arm_db_check Database is current. Head: 469d88477c13DB: 469d88477c13
[2023-11-27 02:44:12,267] DEBUG ARM: utils.arm_db_cfg UISettings: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x7f0c2138f1c0>) (language=en) (id=1) (save_remote_images=True) (database_limit=200) (bootstrap_skin=spacelab) (use_icons=True) (index_refresh=2000) (notify_refresh=6500)
[2023-11-27 02:44:12,271] DEBUG ARM: utils.arm_alembic_get Alembic Head is: 469d88477c13
[2023-11-27 02:44:12,273] DEBUG ARM: utils.arm_db_get Database Head is: 469d88477c13
[2023-11-27 02:44:12,273] DEBUG ARM: utils.arm_db_check Database is current. Head: 469d88477c13DB: 469d88477c13
[2023-11-27 02:44:12,273] DEBUG ARM: utils.arm_db_cfg UISettings: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x7f0c2138f1c0>) (language=en) (id=1) (save_remote_images=True) (database_limit=200) (bootstrap_skin=spacelab) (use_icons=True) (index_refresh=2000) (notify_refresh=6500)
[2023-11-27 02:44:12,321] DEBUG ARM: job.parse_udev pyudev: DEVLINKS: /dev/disk/by-path/pci-0000:00:1a.7-usb-0:4:1.0-scsi-0:0:0:0 /dev/dvdrw /dev/dvd /dev/cdrw /dev/disk/by-id/usb-PIONEER_DVD-RW_DVR-110D-0:0
[2023-11-27 02:44:12,322] DEBUG ARM: job.parse_udev pyudev: DEVNAME: /dev/sr1
[2023-11-27 02:44:12,322] DEBUG ARM: job.parse_udev pyudev: DEVPATH: /devices/pci0000:00/0000:00:1a.7/usb1/1-4/1-4:1.0/host4/target4:0:0/4:0:0:0/block/sr1
[2023-11-27 02:44:12,322] DEBUG ARM: job.parse_udev pyudev: DEVTYPE: disk
[2023-11-27 02:44:12,323] DEBUG ARM: job.parse_udev pyudev: DISKSEQ: 248
[2023-11-27 02:44:12,323] DEBUG ARM: job.parse_udev pyudev: ID_BUS: usb
[2023-11-27 02:44:12,323] DEBUG ARM: job.parse_udev pyudev: ID_CDROM: 1
[2023-11-27 02:44:12,323] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_CD: 1
[2023-11-27 02:44:12,324] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_CD_R: 1
[2023-11-27 02:44:12,324] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_CD_RW: 1
[2023-11-27 02:44:12,325] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_DVD: 1
[2023-11-27 02:44:12,325] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_DVD_PLUS_R: 1
[2023-11-27 02:44:12,325] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_DVD_PLUS_RW: 1
[2023-11-27 02:44:12,326] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_DVD_PLUS_R_DL: 1
[2023-11-27 02:44:12,326] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_DVD_R: 1
[2023-11-27 02:44:12,326] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_DVD_RW: 1
[2023-11-27 02:44:12,326] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_MEDIA: 1
[2023-11-27 02:44:12,327] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_MEDIA_CD: 1
[2023-11-27 02:44:12,327] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_MEDIA_SESSION_COUNT: 1
[2023-11-27 02:44:12,327] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_MEDIA_TRACK_COUNT: 18
[2023-11-27 02:44:12,328] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_MEDIA_TRACK_COUNT_AUDIO: 18
[2023-11-27 02:44:12,328] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_MRW: 1
[2023-11-27 02:44:12,328] DEBUG ARM: job.parse_udev pyudev: ID_CDROM_MRW_W: 1
[2023-11-27 02:44:12,329] DEBUG ARM: job.parse_udev pyudev: ID_FOR_SEAT: block-pci-0000_00_1a_7-usb-0_4_1_0-scsi-0_0_0_0
[2023-11-27 02:44:12,329] DEBUG ARM: job.parse_udev pyudev: ID_INSTANCE: 0:0
[2023-11-27 02:44:12,329] DEBUG ARM: job.parse_udev pyudev: ID_MODEL: DVD-RW_DVR-110D
[2023-11-27 02:44:12,330] DEBUG ARM: job.parse_udev pyudev: ID_MODEL_ENC: DVD-RW\x20\x20DVR-110D
[2023-11-27 02:44:12,330] DEBUG ARM: job.parse_udev pyudev: ID_MODEL_ID: 0701
[2023-11-27 02:44:12,330] DEBUG ARM: job.parse_udev pyudev: ID_PATH: pci-0000:00:1a.7-usb-0:4:1.0-scsi-0:0:0:0
[2023-11-27 02:44:12,330] DEBUG ARM: job.parse_udev pyudev: ID_PATH_TAG: pci-0000_00_1a_7-usb-0_4_1_0-scsi-0_0_0_0
[2023-11-27 02:44:12,331] DEBUG ARM: job.parse_udev pyudev: ID_REVISION: 1.17
[2023-11-27 02:44:12,331] DEBUG ARM: job.parse_udev pyudev: ID_SERIAL: PIONEER_DVD-RW_DVR-110D-0:0
[2023-11-27 02:44:12,331] DEBUG ARM: job.parse_udev pyudev: ID_TYPE: cd
[2023-11-27 02:44:12,332] DEBUG ARM: job.parse_udev pyudev: ID_USB_DRIVER: usb-storage
[2023-11-27 02:44:12,332] DEBUG ARM: job.parse_udev pyudev: ID_USB_INTERFACES: :080250:
[2023-11-27 02:44:12,332] DEBUG ARM: job.parse_udev pyudev: ID_USB_INTERFACE_NUM: 00
[2023-11-27 02:44:12,333] DEBUG ARM: job.parse_udev pyudev: ID_VENDOR: PIONEER
[2023-11-27 02:44:12,333] DEBUG ARM: job.parse_udev pyudev: ID_VENDOR_ENC: PIONEER\x20
[2023-11-27 02:44:12,333] DEBUG ARM: job.parse_udev pyudev: ID_VENDOR_ID: 05e3
[2023-11-27 02:44:12,334] DEBUG ARM: job.parse_udev pyudev: MAJOR: 11
[2023-11-27 02:44:12,334] DEBUG ARM: job.parse_udev pyudev: MINOR: 1
[2023-11-27 02:44:12,334] DEBUG ARM: job.parse_udev pyudev: SUBSYSTEM: block
[2023-11-27 02:44:12,335] DEBUG ARM: job.parse_udev pyudev: SYSTEMD_MOUNT_DEVICE_BOUND: 1
[2023-11-27 02:44:12,335] DEBUG ARM: job.parse_udev pyudev: TAGS: :uaccess:seat:systemd:
[2023-11-27 02:44:12,335] DEBUG ARM: job.parse_udev pyudev: USEC_INITIALIZED: 500859549126
[2023-11-27 02:44:12,528] DEBUG ARM: job.identify_audio_cd music_id: Uej56Alm8YoN9wjuNKFu9ZPIhwo-
[2023-11-27 02:44:12,529] DEBUG ARM: musicbrainz.set_useragent set user-agent to arm/v2_devel python-musicbrainzngs/0.7.1
[2023-11-27 02:44:12,529] DEBUG ARM: musicbrainz._mb_request GET request for https://musicbrainz.org/ws/2/discid/Uej56Alm8YoN9wjuNKFu9ZPIhwo-?inc=artist-credits
[2023-11-27 02:44:12,531] DEBUG ARM: musicbrainz._mb_request requesting with UA arm/v2_devel python-musicbrainzngs/0.7.1
[2023-11-27 02:44:13,415] INFO ARM: mbxml.parse_attributes in <ws2:artist>, uncaught attribute type-id
[2023-11-27 02:44:13,417] INFO ARM: mbxml.parse_attributes in <ws2:artist>, uncaught attribute type-id
[2023-11-27 02:44:13,418] INFO ARM: mbxml.parse_attributes in <ws2:artist>, uncaught attribute type-id
[2023-11-27 02:44:13,419] INFO ARM: mbxml.parse_attributes in <ws2:artist>, uncaught attribute type-id
[2023-11-27 02:44:13,420] INFO ARM: mbxml.parse_attributes in <ws2:artist>, uncaught attribute type-id
[2023-11-27 02:44:13,420] INFO ARM: mbxml.parse_attributes in <ws2:artist>, uncaught attribute type-id
[2023-11-27 02:44:13,421] INFO ARM: mbxml.parse_attributes in <ws2:artist>, uncaught attribute type-id
[2023-11-27 02:44:13,422] INFO ARM: mbxml.parse_attributes in <ws2:artist>, uncaught attribute type-id
[2023-11-27 02:44:13,423] INFO ARM: mbxml.parse_attributes in <ws2:artist>, uncaught attribute type-id
[2023-11-27 02:44:13,424] INFO ARM: mbxml.parse_attributes in <ws2:artist>, uncaught attribute type-id
[2023-11-27 02:44:13,425] DEBUG ARM: music_brainz.get_title Infos: {'disc': {'id': 'Uej56Alm8YoN9wjuNKFu9ZPIhwo-', 'sectors': '284497', 'offset-list': [150, 15800, 33755, 51842, 71605, 88860, 102382, 118612, 137645, 153975, 158627, 175512, 182627, 202025, 217442, 239087, 248777, 268170], 'offset-count': 18, 'release-list': [{'id': '679841df-599d-402f-9f89-0d0bb6e94368', 'title': 'Play', 'status': 'Official', 'quality': 'normal', 'packaging': 'Jewel Case', 'text-representation': {'language': 'eng', 'script': 'Latn'}, 'artist-credit': [{'artist': {'id': '8970d868-0723-483b-a75b-51088913d3d4', 'type': 'Person', 'name': 'Moby', 'sort-name': 'Moby', 'disambiguation': 'electronic musician Richard Melville Hall'}}], 'date': '1999-06-01', 'country': 'US', 'release-event-list': [{'date': '1999-06-01', 'area': {'id': '489ce91b-6658-3307-9877-795b68554c98', 'name': 'United States', 'sort-name': 'United States', 'iso-3166-1-code-list': ['US']}}], 'release-event-count': 1, 'barcode': '638812704924', 'asin': 'B00000J6AG', 'cover-art-archive': {'artwork': 'true', 'count': '1', 'front': 'true', 'back': 'false'}, 'medium-list': [{'position': '1', 'format': 'CD', 'disc-list': [{'id': '5qo5UGeX4TShw9I1jFzws9cXvPM-', 'sectors': '285693', 'offset-list': [150, 15871, 33897, 52055, 71989, 89290, 102805, 119108, 138212, 154613, 159336, 176292, 183478, 202947, 218435, 240151, 249912, 269376], 'offset-count': 18}, {'id': '6rqZnccxwrNRSrbMQpga76nxi8Y-', 'sectors': '284470', 'offset-list': [150, 15797, 33752, 51837, 71587, 88857, 102377, 118610, 137642, 153972, 158622, 175510, 182625, 202022, 217440, 239085, 248772, 268170], 'offset-count': 18}, {'id': 'ILE.c7LVuxyUINv3uf6ex0Jb3dQ-', 'sectors': '285161', 'offset-list': [150, 15902, 33879, 51986, 71879, 89151, 102651, 118893, 137953, 154318, 159015, 175904, 183082, 202526, 217983, 239661, 249367, 268768], 'offset-count': 18}, {'id': 'JA9uGF982rCaxZQelCipsxr1FXM-', 'sectors': '284630', 'offset-list': [150, 15830, 33785, 51870, 71735, 88965, 102485, 118717, 137750, 154097, 158732, 175617, 182730, 202130, 217555, 239192, 248880, 268282], 'offset-count': 18}, {'id': 'MNEZ.lH5fKXwnGgzv7c1VPhHgi4-', 'sectors': '284569', 'offset-list': [150, 15798, 33754, 51841, 71704, 88934, 102454, 118687, 137719, 154048, 158701, 175587, 182701, 202099, 217517, 239161, 248851, 268244], 'offset-count': 18}, {'id': 'No50WABdXr2lKMi59jRDMGkfzV4-', 'sectors': '285223', 'offset-list': [150, 15843, 33840, 51969, 71775, 89073, 102637, 118910, 137985, 154358, 159052, 175980, 183137, 202578, 218038, 239724, 249456, 268891], 'offset-count': 18}, {'id': 'PDSaNWNlRdgk3oX1gHMmFLMcn94-', 'sectors': '287148', 'offset-list': [150, 15952, 34059, 52298, 72313, 89695, 103367, 119751, 138936, 155418, 160222, 177259, 184526, 204076, 219645, 241442, 251284, 270829], 'offset-count': 18}, {'id': 'RRcrags4LSB9lwFJnGnzLryAfGQ-', 'sectors': '285061', 'offset-list': [150, 15842, 33821, 51930, 71826, 89100, 102602, 118846, 137909, 154276, 158975, 175867, 183047, 202494, 217953, 239634, 249342, 268746], 'offset-count': 18}, {'id': 'TDWrTJkwWg7flV0Z7HPDy4w1Y1M-', 'sectors': '285717', 'offset-list': [150, 15862, 33884, 52013, 71943, 89240, 102802, 119076, 138176, 154575, 159294, 176221, 183488, 203038, 218522, 240234, 249966, 269401], 'offset-count': 18}, {'id': 'Uej56Alm8YoN9wjuNKFu9ZPIhwo-', 'sectors': '284497', 'offset-list': [150, 15800, 33755, 51842, 71605, 88860, 102382, 118612, 137645, 153975, 158627, 175512, 182627, 202025, 217442, 239087, 248777, 268170], 'offset-count': 18}, {'id': 'cG.VeNwZm4a7OSkexAzZ4S2RhIU-', 'sectors': '284540', 'offset-list': [150, 15800, 33755, 51840, 71705, 88935, 102455, 118687, 137720, 154067, 158702, 175587, 182700, 202100, 217525, 239162, 248850, 268252], 'offset-count': 18}, {'id': 'dyxEcw.E6UX5lqK2IycFcMURyFE-', 'sectors': '284700', 'offset-list': [150, 15862, 33817, 51905, 71767, 88997, 102517, 118750, 137782, 154112, 158765, 175650, 182765, 202162, 217580, 239225, 248915, 268307], 'offset-count': 18}, {'id': 'fqzLHNDAJ_Wh3TP1rWRG7F_P62c-', 'sectors': '284750', 'offset-list': [150, 15862, 33817, 51905, 71767, 88997, 102517, 118750, 137782, 154112, 158765, 175650, 182765, 202162, 217580, 239225, 248915, 268307], 'offset-count': 18}, {'id': 'lXa0xk6DI_yVSApgeIdBHkdcoYQ-', 'sectors': '282719', 'offset-list': [150, 15704, 33545, 51516, 71275, 88411, 101776, 117882, 136807, 153036, 157597, 174351, 181394, 200703, 216024, 237567, 247138, 266404], 'offset-count': 18}, {'id': 'm_iYedQMN74ix3_T31dOKf2i9f8-', 'sectors': '284562', 'offset-list': [150, 15800, 33755, 51842, 71705, 88935, 102455, 118687, 137720, 154050, 158702, 175587, 182702, 202100, 217517, 239162, 248852, 268245], 'offset-count': 18}, {'id': 'p5rco_Vix7o526Y4vyFV835jiNQ-', 'sectors': '284560', 'offset-list': [150, 15797, 33752, 51840, 71705, 88932, 102452, 118685, 137717, 154047, 158697, 175585, 182710, 202110, 217522, 239170, 248850, 268242], 'offset-count': 18}, {'id': 'qq1m2aB1_CGs09vlGGjv7hil4J8-', 'sectors': '284560', 'offset-list': [150, 15800, 33755, 51842, 71705, 88935, 102455, 118687, 137720, 154050, 158702, 175587, 182702, 202100, 217517, 239162, 248852, 268245], 'offset-count': 18}], 'disc-count': 17, 'track-list': [], 'track-count': 18}], 'medium-count': 1, 'artist-credit-phrase': 'Moby'}, {'id': '025d4f1a-2e0a-3e0e-9808-f91f77340cf4', 'title': 'Play', 'status': 'Official', 'quality': 'normal', 'packaging': 'Jewel Case', 'text-representation': {'language': 'eng', 'script': 'Latn'}, 'artist-credit': [{'artist': {'id': '8970d868-0723-483b-a75b-51088913d3d4', 'type': 'Person', 'name': 'Moby', 'sort-name': 'Moby', 'disambiguation': 'electronic musician Richard Melville Hall'}}], 'date': '1999-05-17', 'country': 'GB', 'release-event-list': [{'date': '1999-05-17', 'area': {'id': '8a754a16-0027-3a29-b6d7-2b40ea0481ed', 'name': 'United Kingdom', 'sort-name': 'United Kingdom', 'iso-3166-1-code-list': ['GB']}}], 'release-event-count': 1, 'barcode': '5016025611720', 'asin': 'B00000JCXD', 'cover-art-archive': {'artwork': 'true', 'count': '12', 'front': 'true', 'back': 'true'}, 'medium-list': [{'position': '1', 'format': 'CD', 'disc-list': [{'id': '.hOCBlBthLN7N.56L2ziaCqJo7c-', 'sectors': '284559', 'offset-list': [150, 15797, 33752, 51840, 71705, 88932, 102452, 118685, 137717, 154047, 158697, 175585, 182710, 202110, 217522, 239170, 248850, 268242], 'offset-count': 18}, {'id': '56tOXzCwkTClR_Tks8jfeJ74Lhs-', 'sectors': '285143', 'offset-list': [150, 15901, 33877, 51983, 71875, 89146, 102645, 118886, 137945, 154309, 159005, 175893, 183069, 202512, 217968, 239645, 249350, 268750], 'offset-count': 18}, {'id': '5qo5UGeX4TShw9I1jFzws9cXvPM-', 'sectors': '285693', 'offset-list': [150, 15871, 33897, 52055, 71989, 89290, 102805, 119108, 138212, 154613, 159336, 176292, 183478, 202947, 218435, 240151, 249912, 269376], 'offset-count': 18}, {'id': '6rqZnccxwrNRSrbMQpga76nxi8Y-', 'sectors': '284470', 'offset-list': [150, 15797, 33752, 51837, 71587, 88857, 102377, 118610, 137642, 153972, 158622, 175510, 182625, 202022, 217440, 239085, 248772, 268170], 'offset-count': 18}, {'id': '8kFI0lcZNXW2JXryStJIP1Q6KQ4-', 'sectors': '285837', 'offset-list': [150, 15875, 33905, 52067, 72005, 89310, 102905, 119212, 138320, 154725, 159452, 176412, 183602, 203075, 218567, 240287, 250052, 269520], 'offset-count': 18}, {'id': 'Gcw4fq6BSZ4RbumpApOzU3U2owQ-', 'sectors': '287104', 'offset-list': [150, 15945, 34051, 52285, 72296, 89674, 103345, 119725, 138897, 155381, 160189, 177222, 184490, 204038, 219605, 241405, 251244, 270785], 'offset-count': 18}, {'id': 'ILE.c7LVuxyUINv3uf6ex0Jb3dQ-', 'sectors': '285161', 'offset-list': [150, 15902, 33879, 51986, 71879, 89151, 102651, 118893, 137953, 154318, 159015, 175904, 183082, 202526, 217983, 239661, 249367, 268768], 'offset-count': 18}, {'id': 'JA9uGF982rCaxZQelCipsxr1FXM-', 'sectors': '284630', 'offset-list': [150, 15830, 33785, 51870, 71735, 88965, 102485, 118717, 137750, 154097, 158732, 175617, 182730, 202130, 217555, 239192, 248880, 268282], 'offset-count': 18}, {'id': 'MNEZ.lH5fKXwnGgzv7c1VPhHgi4-', 'sectors': '284569', 'offset-list': [150, 15798, 33754, 51841, 71704, 88934, 102454, 118687, 137719, 154048, 158701, 175587, 182701, 202099, 217517, 239161, 248851, 268244], 'offset-count': 18}, {'id': 'PDSaNWNlRdgk3oX1gHMmFLMcn94-', 'sectors': '287148', 'offset-list': [150, 15952, 34059, 52298, 72313, 89695, 103367, 119751, 138936, 155418, 160222, 177259, 184526, 204076, 219645, 241442, 251284, 270829], 'offset-count': 18}, {'id': 'RRcrags4LSB9lwFJnGnzLryAfGQ-', 'sectors': '285061', 'offset-list': [150, 15842, 33821, 51930, 71826, 89100, 102602, 118846, 137909, 154276, 158975, 175867, 183047, 202494, 217953, 239634, 249342, 268746], 'offset-count': 18}, {'id': 'TDWrTJkwWg7flV0Z7HPDy4w1Y1M-', 'sectors': '285717', 'offset-list': [150, 15862, 33884, 52013, 71943, 89240, 102802, 119076, 138176, 154575, 159294, 176221, 183488, 203038, 218522, 240234, 249966, 269401], 'offset-count': 18}, {'id': 'Uej56Alm8YoN9wjuNKFu9ZPIhwo-', 'sectors': '284497', 'offset-list': [150, 15800, 33755, 51842, 71605, 88860, 102382, 118612, 137645, 153975, 158627, 175512, 182627, 202025, 217442, 239087, 248777, 268170], 'offset-count': 18}, {'id': 'dyxEcw.E6UX5lqK2IycFcMURyFE-', 'sectors': '284700', 'offset-list': [150, 15862, 33817, 51905, 71767, 88997, 102517, 118750, 137782, 154112, 158765, 175650, 182765, 202162, 217580, 239225, 248915, 268307], 'offset-count': 18}, {'id': 'fqzLHNDAJ_Wh3TP1rWRG7F_P62c-', 'sectors': '284750', 'offset-list': [150, 15862, 33817, 51905, 71767, 88997, 102517, 118750, 137782, 154112, 158765, 175650, 182765, 202162, 217580, 239225, 248915, 268307], 'offset-count': 18}, {'id': 'kY_LDYc4yVUzig5E9IYDVghvJwY-', 'sectors': '285001', 'offset-list': [150, 15813, 33759, 51834, 71699, 88933, 102451, 118681, 137713, 154064, 158704, 175586, 182728, 202096, 217523, 239205, 248858, 268393], 'offset-count': 18}, {'id': 'lXa0xk6DI_yVSApgeIdBHkdcoYQ-', 'sectors': '282719', 'offset-list': [150, 15704, 33545, 51516, 71275, 88411, 101776, 117882, 136807, 153036, 157597, 174351, 181394, 200703, 216024, 237567, 247138, 266404], 'offset-count': 18}, {'id': 'm_iYedQMN74ix3_T31dOKf2i9f8-', 'sectors': '284562', 'offset-list': [150, 15800, 33755, 51842, 71705, 88935, 102455, 118687, 137720, 154050, 158702, 175587, 182702, 202100, 217517, 239162, 248852, 268245], 'offset-count': 18}, {'id': 'p5rco_Vix7o526Y4vyFV835jiNQ-', 'sectors': '284560', 'offset-list': [150, 15797, 33752, 51840, 71705, 88932, 102452, 118685, 137717, 154047, 158697, 175585, 182710, 202110, 217522, 239170, 248850, 268242], 'offset-count': 18}, {'id': 'qBitE3x.bqnjzmQs5rc5mBIRlSM-', 'sectors': '284692', 'offset-list': [150, 15852, 33807, 51909, 71757, 88987, 102507, 118740, 137784, 154102, 158755, 175640, 182755, 202152, 217584, 239214, 248905, 268297], 'offset-count': 18}, {'id': 'qq1m2aB1_CGs09vlGGjv7hil4J8-', 'sectors': '284560', 'offset-list': [150, 15800, 33755, 51842, 71705, 88935, 102455, 118687, 137720, 154050, 158702, 175587, 182702, 202100, 217517, 239162, 248852, 268245], 'offset-count': 18}, {'id': 'x0f2cKp7dzqRlL3Xc8_ajS83FHg-', 'sectors': '282700', 'offset-list': [150, 15703, 33543, 51513, 71270, 88405, 101768, 117873, 136797, 153025, 157585, 174338, 181380, 200688, 216008, 237550, 247120, 266385], 'offset-count': 18}], 'disc-count': 22, 'track-list': [], 'track-count': 18}], 'medium-count': 1, 'artist-credit-phrase': 'Moby'}, {'id': '218cecee-c862-39ce-bbb2-25e0bad1a6c4', 'title': 'Play', 'status': 'Official', 'quality': 'normal', 'text-representation': {'language': 'eng', 'script': 'Latn'}, 'artist-credit': [{'artist': {'id': '8970d868-0723-483b-a75b-51088913d3d4', 'type': 'Person', 'name': 'Moby', 'sort-name': 'Moby', 'disambiguation': 'electronic musician Richard Melville Hall'}}], 'date': '2000-10-23', 'country': 'GB', 'release-event-list': [{'date': '2000-10-23', 'area': {'id': '8a754a16-0027-3a29-b6d7-2b40ea0481ed', 'name': 'United Kingdom', 'sort-name': 'United Kingdom', 'iso-3166-1-code-list': ['GB']}}], 'release-event-count': 1, 'barcode': '5016025511723', 'asin': 'B00004Y262', 'cover-art-archive': {'artwork': 'true', 'count': '1', 'front': 'true', 'back': 'false'}, 'medium-list': [{'position': '1', 'format': 'CD', 'disc-list': [{'id': '5qo5UGeX4TShw9I1jFzws9cXvPM-', 'sectors': '285693', 'offset-list': [150, 15871, 33897, 52055, 71989, 89290, 102805, 119108, 138212, 154613, 159336, 176292, 183478, 202947, 218435, 240151, 249912, 269376], 'offset-count': 18}, {'id': '6rqZnccxwrNRSrbMQpga76nxi8Y-', 'sectors': '284470', 'offset-list': [150, 15797, 33752, 51837, 71587, 88857, 102377, 118610, 137642, 153972, 158622, 175510, 182625, 202022, 217440, 239085, 248772, 268170], 'offset-count': 18}, {'id': 'ILE.c7LVuxyUINv3uf6ex0Jb3dQ-', 'sectors': '285161', 'offset-list': [150, 15902, 33879, 51986, 71879, 89151, 102651, 118893, 137953, 154318, 159015, 175904, 183082, 202526, 217983, 239661, 249367, 268768], 'offset-count': 18}, {'id': 'JA9uGF982rCaxZQelCipsxr1FXM-', 'sectors': '284630', 'offset-list': [150, 15830, 33785, 51870, 71735, 88965, 102485, 118717, 137750, 154097, 158732, 175617, 182730, 202130, 217555, 239192, 248880, 268282], 'offset-count': 18}, {'id': 'MNEZ.lH5fKXwnGgzv7c1VPhHgi4-', 'sectors': '284569', 'offset-list': [150, 15798, 33754, 51841, 71704, 88934, 102454, 118687, 137719, 154048, 158701, 175587, 182701, 202099, 217517, 239161, 248851, 268244], 'offset-count': 18}, {'id': 'PDSaNWNlRdgk3oX1gHMmFLMcn94-', 'sectors': '287148', 'offset-list': [150, 15952, 34059, 52298, 72313, 89695, 103367, 119751, 138936, 155418, 160222, 177259, 184526, 204076, 219645, 241442, 251284, 270829], 'offset-count': 18}, {'id': 'RRcrags4LSB9lwFJnGnzLryAfGQ-', 'sectors': '285061', 'offset-list': [150, 15842, 33821, 51930, 71826, 89100, 102602, 118846, 137909, 154276, 158975, 175867, 183047, 202494, 217953, 239634, 249342, 268746], 'offset-count': 18}, {'id': 'TDWrTJkwWg7flV0Z7HPDy4w1Y1M-', 'sectors': '285717', 'offset-list': [150, 15862, 33884, 52013, 71943, 89240, 102802, 119076, 138176, 154575, 159294, 176221, 183488, 203038, 218522, 240234, 249966, 269401], 'offset-count': 18}, {'id': 'Uej56Alm8YoN9wjuNKFu9ZPIhwo-', 'sectors': '284497', 'offset-list': [150, 15800, 33755, 51842, 71605, 88860, 102382, 118612, 137645, 153975, 158627, 175512, 182627, 202025, 217442, 239087, 248777, 268170], 'offset-count': 18}, {'id': 'cG.VeNwZm4a7OSkexAzZ4S2RhIU-', 'sectors': '284540', 'offset-list': [150, 15800, 33755, 51840, 71705, 88935, 102455, 118687, 137720, 154067, 158702, 175587, 182700, 202100, 217525, 239162, 248850, 268252], 'offset-count': 18}, {'id': 'dyxEcw.E6UX5lqK2IycFcMURyFE-', 'sectors': '284700', 'offset-list': [150, 15862, 33817, 51905, 71767, 88997, 102517, 118750, 137782, 154112, 158765, 175650, 182765, 202162, 217580, 239225, 248915, 268307], 'offset-count': 18}, {'id': 'fqzLHNDAJ_Wh3TP1rWRG7F_P62c-', 'sectors': '284750', 'offset-list': [150, 15862, 33817, 51905, 71767, 88997, 102517, 118750, 137782, 154112, 158765, 175650, 182765, 202162, 217580, 239225, 248915, 268307], 'offset-count': 18}, {'id': 'lXa0xk6DI_yVSApgeIdBHkdcoYQ-', 'sectors': '282719', 'offset-list': [150, 15704, 33545, 51516, 71275, 88411, 101776, 117882, 136807, 153036, 157597, 174351, 181394, 200703, 216024, 237567, 247138, 266404], 'offset-count': 18}, {'id': 'm_iYedQMN74ix3_T31dOKf2i9f8-', 'sectors': '284562', 'offset-list': [150, 15800, 33755, 51842, 71705, 88935, 102455, 118687, 137720, 154050, 158702, 175587, 182702, 202100, 217517, 239162, 248852, 268245], 'offset-count': 18}, {'id': 'p5rco_Vix7o526Y4vyFV835jiNQ-', 'sectors': '284560', 'offset-list': [150, 15797, 33752, 51840, 71705, 88932, 102452, 118685, 137717, 154047, 158697, 175585, 182710, 202110, 217522, 239170, 248850, 268242], 'offset-count': 18}, {'id': 'qq1m2aB1_CGs09vlGGjv7hil4J8-', 'sectors': '284560', 'offset-list': [150, 15800, 33755, 51842, 71705, 88935, 102455, 118687, 137720, 154050, 158702, 175587, 182702, 202100, 217517, 239162, 248852, 268245], 'offset-count': 18}], 'disc-count': 16, 'track-list': [], 'track-count': 18}, {'title': 'The B Sides', 'position': '2', 'format': 'CD', 'disc-list': [{'id': 'Iz5AAa7sb2K0BdLU0yF1JpVeYZY-', 'sectors': '273220', 'offset-list': [150, 15622, 38380, 68532, 95732, 122585, 141240, 169470, 200175, 221727, 253657], 'offset-count': 11}, {'id': 'gehT7A.F69g1Bv4F0KcdVV8A0tw-', 'sectors': '273165', 'offset-list': [150, 15564, 38341, 68505, 95718, 122587, 141249, 169503, 200222, 221793, 253734], 'offset-count': 11}, {'id': 'h1i4vnE3gl4WXWVquhJNG9DlSi8-', 'sectors': '273220', 'offset-list': [150, 15623, 38378, 68533, 95733, 122583, 141240, 169470, 200175, 221728, 253658], 'offset-count': 11}, {'id': 'o5OnewshYFUPEPneFLnFCLrP.iQ-', 'sectors': '273196', 'offset-list': [150, 15620, 38376, 68526, 95724, 122575, 141227, 169455, 200158, 221708, 253635], 'offset-count': 11}, {'id': 'uQt33TT8IzzPqEdaLvkJtQRLKVQ-', 'sectors': '273045', 'offset-list': [150, 15560, 38317, 68470, 95670, 122522, 141177, 169407, 200112, 221665, 253595], 'offset-count': 11}], 'disc-count': 5, 'track-list': [], 'track-count': 11}], 'medium-count': 2, 'artist-credit-phrase': 'Moby'}, {'id': '9b75ccb5-fa55-3589-ad11-700d8bc8da12', 'title': 'Play', 'status': 'Official', 'quality': 'normal', 'text-representation': {'language': 'eng', 'script': 'Latn'}, 'artist-credit': [{'artist': {'id': '8970d868-0723-483b-a75b-51088913d3d4', 'type': 'Person', 'name': 'Moby', 'sort-name': 'Moby', 'disambiguation': 'electronic musician Richard Melville Hall'}}], 'date': '2000-07-03', 'country': 'DE', 'release-event-list': [{'date': '2000-07-03', 'area': {'id': '85752fda-13c4-31a3-bee5-0e5cb1f51dad', 'name': 'Germany', 'sort-name': 'Germany', 'iso-3166-1-code-list': ['DE']}}], 'release-event-count': 1, 'barcode': '5413356762822', 'asin': 'B00004UB37', 'cover-art-archive': {'artwork': 'false', 'count': '0', 'front': 'false', 'back': 'false'}, 'medium-list': [{'position': '1', 'format': 'CD', 'disc-list': [{'id': '5qo5UGeX4TShw9I1jFzws9cXvPM-', 'sectors': '285693', 'offset-list': [150, 15871, 33897, 52055, 71989, 89290, 102805, 119108, 138212, 154613, 159336, 176292, 183478, 202947, 218435, 240151, 249912, 269376], 'offset-count': 18}, {'id': '6rqZnccxwrNRSrbMQpga76nxi8Y-', 'sectors': '284470', 'offset-list': [150, 15797, 33752, 51837, 71587, 88857, 102377, 118610, 137642, 153972, 158622, 175510, 182625, 202022, 217440, 239085, 248772, 268170], 'offset-count': 18}, {'id': 'ILE.c7LVuxyUINv3uf6ex0Jb3dQ-', 'sectors': '285161', 'offset-list': [150, 15902, 33879, 51986, 71879, 89151, 102651, 118893, 137953, 154318, 159015, 175904, 183082, 202526, 217983, 239661, 249367, 268768], 'offset-count': 18}, {'id': 'JA9uGF982rCaxZQelCipsxr1FXM-', 'sectors': '284630', 'offset-list': [150, 15830, 33785, 51870, 71735, 88965, 102485, 118717, 137750, 154097, 158732, 175617, 182730, 202130, 217555, 239192, 248880, 268282], 'offset-count': 18}, {'id': 'MNEZ.lH5fKXwnGgzv7c1VPhHgi4-', 'sectors': '284569', 'offset-list': [150, 15798, 33754, 51841, 71704, 88934, 102454, 118687, 137719, 154048, 158701, 175587, 182701, 202099, 217517, 239161, 248851, 268244], 'offset-count': 18}, {'id': 'PDSaNWNlRdgk3oX1gHMmFLMcn94-', 'sectors': '287148', 'offset-list': [150, 15952, 34059, 52298, 72313, 89695, 103367, 119751, 138936, 155418, 160222, 177259, 184526, 204076, 219645, 241442, 251284, 270829], 'offset-count': 18}, {'id': 'RRcrags4LSB9lwFJnGnzLryAfGQ-', 'sectors': '285061', 'offset-list': [150, 15842, 33821, 51930, 71826, 89100, 102602, 118846, 137909, 154276, 158975, 175867, 183047, 202494, 217953, 239634, 249342, 268746], 'offset-count': 18}, {'id': 'TDWrTJkwWg7flV0Z7HPDy4w1Y1M-', 'sectors': '285717', 'offset-list': [150, 15862, 33884, 52013, 71943, 89240, 102802, 119076, 138176, 154575, 159294, 176221, 183488, 203038, 218522, 240234, 249966, 269401], 'offset-count': 18}, {'id': 'Uej56Alm8YoN9wjuNKFu9ZPIhwo-', 'sectors': '284497', 'offset-list': [150, 15800, 33755, 51842, 71605, 88860, 102382, 118612, 137645, 153975, 158627, 175512, 182627, 202025, 217442, 239087, 248777, 268170], 'offset-count': 18}, {'id': 'cG.VeNwZm4a7OSkexAzZ4S2RhIU-', 'sectors': '284540', 'offset-list': [150, 15800, 33755, 51840, 71705, 88935, 102455, 118687, 137720, 154067, 158702, 175587, 182700, 202100, 217525, 239162, 248850, 268252], 'offset-count': 18}, {'id': 'dyxEcw.E6UX5lqK2IycFcMURyFE-', 'sectors': '284700', 'offset-list': [150, 15862, 33817, 51905, 71767, 88997, 102517, 118750, 137782, 154112, 158765, 175650, 182765, 202162, 217580, 239225, 248915, 268307], 'offset-count': 18}, {'id': 'fqzLHNDAJ_Wh3TP1rWRG7F_P62c-', 'sectors': '284750', 'offset-list': [150, 15862, 33817, 51905, 71767, 88997, 102517, 118750, 137782, 154112, 158765, 175650, 182765, 202162, 217580, 239225, 248915, 268307], 'offset-count': 18}, {'id': 'lXa0xk6DI_yVSApgeIdBHkdcoYQ-', 'sectors': '282719', 'offset-list': [150, 15704, 33545, 51516, 71275, 88411, 101776, 117882, 136807, 153036, 157597, 174351, 181394, 200703, 216024, 237567, 247138, 266404], 'offset-count': 18}, {'id': 'm_iYedQMN74ix3_T31dOKf2i9f8-', 'sectors': '284562', 'offset-list': [150, 15800, 33755, 51842, 71705, 88935, 102455, 118687, 137720, 154050, 158702, 175587, 182702, 202100, 217517, 239162, 248852, 268245], 'offset-count': 18}, {'id': 'p5rco_Vix7o526Y4vyFV835jiNQ-', 'sectors': '284560', 'offset-list': [150, 15797, 33752, 51840, 71705, 88932, 102452, 118685, 137717, 154047, 158697, 175585, 182710, 202110, 217522, 239170, 248850, 268242], 'offset-count': 18}, {'id': 'qq1m2aB1_CGs09vlGGjv7hil4J8-', 'sectors': '284560', 'offset-list': [150, 15800, 33755, 51842, 71705, 88935, 102455, 118687, 137720, 154050, 158702, 175587, 182702, 202100, 217517, 239162, 248852, 268245], 'offset-count': 18}], 'disc-count': 16, 'track-list': [], 'track-count': 18}, {'position': '2', 'format': 'CD', 'disc-list': [{'id': 'MBaO74B9igPgio.x1coDEqzOtEI-', 'sectors': '98370', 'offset-list': [150, 18590, 37587, 47367, 73235], 'offset-count': 5}], 'disc-count': 1, 'track-list': [], 'track-count': 5}], 'medium-count': 2, 'artist-credit-phrase': 'Moby'}, {'id': '468ba5e7-d8ab-3536-9a3f-403c9ad4423c', 'title': 'Play', 'status': 'Official', 'quality': 'normal', 'text-representation': {'language': 'eng', 'script': 'Latn'}, 'artist-credit': [{'artist': {'id': '8970d868-0723-483b-a75b-51088913d3d4', 'type': 'Person', 'name': 'Moby', 'sort-name': 'Moby', 'disambiguation': 'electronic musician Richard Melville Hall'}}], 'date': '2000-09-20', 'country': 'JP', 'release-event-list': [{'date': '2000-09-20', 'area': {'id': '2db42837-c832-3c27-b4a3-08198f75693c', 'name': 'Japan', 'sort-name': 'Japan', 'iso-3166-1-code-list': ['JP']}}], 'release-event-count': 1, 'barcode': '0766486334229', 'asin': 'B000050AME', 'cover-art-archive': {'artwork': 'false', 'count': '0', 'front': 'false', 'back': 'false'}, 'medium-list': [{'position': '1', 'format': 'CD', 'disc-list': [{'id': '5qo5UGeX4TShw9I1jFzws9cXvPM-', 'sectors': '285693', 'offset-list': [150, 15871, 33897, 52055, 71989, 89290, 102805, 119108, 138212, 154613, 159336, 176292, 183478, 202947, 218435, 240151, 249912, 269376], 'offset-count': 18}, {'id': '6rqZnccxwrNRSrbMQpga76nxi8Y-', 'sectors': '284470', 'offset-list': [150, 15797, 33752, 51837, 71587, 88857, 102377, 118610, 137642, 153972, 158622, 175510, 182625, 202022, 217440, 239085, 248772, 268170], 'offset-count': 18}, {'id': 'ILE.c7LVuxyUINv3uf6ex0Jb3dQ-', 'sectors': '285161', 'offset-list': [150, 15902, 33879, 51986, 71879, 89151, 102651, 118893, 137953, 154318, 159015, 175904, 183082, 202526, 217983, 239661, 249367, 268768], 'offset-count': 18}, {'id': 'JA9uGF982rCaxZQelCipsxr1FXM-', 'sectors': '284630', 'offset-list': [150, 15830, 33785, 51870, 71735, 88965, 102485, 118717, 137750, 154097, 158732, 175617, 182730, 202130, 217555, 239192, 248880, 268282], 'offset-count': 18}, {'id': 'MNEZ.lH5fKXwnGgzv7c1VPhHgi4-', 'sectors': '284569', 'offset-list': [150, 15798, 33754, 51841, 71704, 88934, 102454, 118687, 137719, 154048, 158701, 175587, 182701, 202099, 217517, 239161, 248851, 268244], 'offset-count': 18}, {'id': 'PDSaNWNlRdgk3oX1gHMmFLMcn94-', 'sectors': '287148', 'offset-list': [150, 15952, 34059, 52298, 72313, 89695, 103367, 119751, 138936, 155418, 160222, 177259, 184526, 204076, 219645, 241442, 251284, 270829], 'offset-count': 18}, {'id': 'RRcrags4LSB9lwFJnGnzLryAfGQ-', 'sectors': '285061', 'offset-list': [150, 15842, 33821, 51930, 71826, 89100, 102602, 118846, 137909, 154276, 158975, 175867, 183047, 202494, 217953, 239634, 249342, 268746], 'offset-count': 18}, {'id': 'TDWrTJkwWg7flV0Z7HPDy4w1Y1M-', 'sectors': '285717', 'offset-list': [150, 15862, 33884, 52013, 71943, 89240, 102802, 119076, 138176, 154575, 159294, 176221, 183488, 203038, 218522, 240234, 249966, 269401], 'offset-count': 18}, {'id': 'Uej56Alm8YoN9wjuNKFu9ZPIhwo-', 'sectors': '284497', 'offset-list': [150, 15800, 33755, 51842, 71605, 88860, 102382, 118612, 137645, 153975, 158627, 175512, 182627, 202025, 217442, 239087, 248777, 268170], 'offset-count': 18}, {'id': 'cG.VeNwZm4a7OSkexAzZ4S2RhIU-', 'sectors': '284540', 'offset-list': [150, 15800, 33755, 51840, 71705, 88935, 102455, 118687, 137720, 154067, 158702, 175587, 182700, 202100, 217525, 239162, 248850, 268252], 'offset-count': 18}, {'id': 'fqzLHNDAJ_Wh3TP1rWRG7F_P62c-', 'sectors': '284750', 'offset-list': [150, 15862, 33817, 51905, 71767, 88997, 102517, 118750, 137782, 154112, 158765, 175650, 182765, 202162, 217580, 239225, 248915, 268307], 'offset-count': 18}, {'id': 'lXa0xk6DI_yVSApgeIdBHkdcoYQ-', 'sectors': '282719', 'offset-list': [150, 15704, 33545, 51516, 71275, 88411, 101776, 117882, 136807, 153036, 157597, 174351, 181394, 200703, 216024, 237567, 247138, 266404], 'offset-count': 18}, {'id': 'm_iYedQMN74ix3_T31dOKf2i9f8-', 'sectors': '284562', 'offset-list': [150, 15800, 33755, 51842, 71705, 88935, 102455, 118687, 137720, 154050, 158702, 175587, 182702, 202100, 217517, 239162, 248852, 268245], 'offset-count': 18}, {'id': 'p5rco_Vix7o526Y4vyFV835jiNQ-', 'sectors': '284560', 'offset-list': [150, 15797, 33752, 51840, 71705, 88932, 102452, 118685, 137717, 154047, 158697, 175585, 182710, 202110, 217522, 239170, 248850, 268242], 'offset-count': 18}, {'id': 'qq1m2aB1_CGs09vlGGjv7hil4J8-', 'sectors': '284560', 'offset-list': [150, 15800, 33755, 51842, 71705, 88935, 102455, 118687, 137720, 154050, 158702, 175587, 182702, 202100, 217517, 239162, 248852, 268245], 'offset-count': 18}], 'disc-count': 15, 'track-list': [], 'track-count': 18}, {'position': '2', 'format': 'CD', 'disc-list': [{'id': 'pr1imW6y_fU_oIQVbymcXh6qrsk-', 'sectors': '86075', 'offset-list': [150, 30050, 66967], 'offset-count': 3}], 'disc-count': 1, 'track-list': [], 'track-count': 3}], 'medium-count': 2, 'artist-credit-phrase': 'Moby'}, {'id': 'fe6900f2-8351-3fd8-a2ba-0b30f116ea54', 'title': 'Play', 'status': 'Official', 'quality': 'normal', 'text-representation': {'language': 'eng', 'script': 'Latn'}, 'artist-credit': [{'artist': {'id': '8970d868-0723-483b-a75b-51088913d3d4', 'type': 'Person', 'name': 'Moby', 'sort-name': 'Moby', 'disambiguation': 'electronic musician Richard Melville Hall'}}], 'date': '2000-05', 'country': 'NL', 'release-event-list': [{'date': '2000-05', 'area': {'id': 'ef1b7cc0-cd26-36f4-8ea0-04d9623786c7', 'name': 'Netherlands', 'sort-name': 'Netherlands', 'iso-3166-1-code-list': ['NL']}}], 'release-event-count': 1, 'barcode': '5413356759624', 'cover-art-archive': {'artwork': 'true', 'count': '1', 'front': 'true', 'back': 'false'}, 'medium-list': [{'position': '1', 'format': 'CD', 'disc-list': [{'id': '5qo5UGeX4TShw9I1jFzws9cXvPM-', 'sectors': '285693', 'offset-list': [150, 15871, 33897, 52055, 71989, 89290, 102805, 119108, 138212, 154613, 159336, 176292, 183478, 202947, 218435, 240151, 249912, 269376], 'offset-count': 18}, {'id': '6rqZnccxwrNRSrbMQpga76nxi8Y-', 'sectors': '284470', 'offset-list': [150, 15797, 33752, 51837, 71587, 88857, 102377, 118610, 137642, 153972, 158622, 175510, 182625, 202022, 217440, 239085, 248772, 268170], 'offset-count': 18}, {'id': 'ILE.c7LVuxyUINv3uf6ex0Jb3dQ-', 'sectors': '285161', 'offset-list': [150, 15902, 33879, 51986, 71879, 89151, 102651, 118893, 137953, 154318, 159015, 175904, 183082, 202526, 217983, 239661, 249367, 268768], 'offset-count': 18}, {'id': 'JA9uGF982rCaxZQelCipsxr1FXM-', 'sectors': '284630', 'offset-list': [150, 15830, 33785, 51870, 71735, 88965, 102485, 118717, 137750, 154097, 158732, 175617, 182730, 202130, 217555, 239192, 248880, 268282], 'offset-count': 18}, {'id': 'MNEZ.lH5fKXwnGgzv7c1VPhHgi4-', 'sectors': '284569', 'offset-list': [150, 15798, 33754, 51841, 71704, 88934, 102454, 118687, 137719, 154048, 158701, 175587, 182701, 202099, 217517, 239161, 248851, 268244], 'offset-count': 18}, {'id': 'PDSaNWNlRdgk3oX1gHMmFLMcn94-', 'sectors': '287148', 'offset-list': [150, 15952, 34059, 52298, 72313, 89695, 103367, 119751, 138936, 155418, 160222, 177259, 184526, 204076, 219645, 241442, 251284, 270829], 'offset-count': 18}, {'id': 'RRcrags4LSB9lwFJnGnzLryAfGQ-', 'sectors': '285061', 'offset-list': [150, 15842, 33821, 51930, 71826, 89100, 102602, 118846, 137909, 154276, 158975, 175867, 183047, 202494, 217953, 239634, 249342, 268746], 'offset-count': 18}, {'id': 'TDWrTJkwWg7flV0Z7HPDy4w1Y1M-', 'sectors': '285717', 'offset-list': [150, 15862, 33884, 52013, 71943, 89240, 102802, 119076, 138176, 154575, 159294, 176221, 183488, 203038, 218522, 240234, 249966, 269401], 'offset-count': 18}, {'id': 'Uej56Alm8YoN9wjuNKFu9ZPIhwo-', 'sectors': '284497', 'offset-list': [150, 15800, 33755, 51842, 71605, 88860, 102382, 118612, 137645, 153975, 158627, 175512, 182627, 202025, 217442, 239087, 248777, 268170], 'offset-count': 18}, {'id': 'cG.VeNwZm4a7OSkexAzZ4S2RhIU-', 'sectors': '284540', 'offset-list': [150, 15800, 33755, 51840, 71705, 88935, 102455, 118687, 137720, 154067, 158702, 175587, 182700, 202100, 217525, 239162, 248850, 268252], 'offset-count': 18}, {'id': 'fqzLHNDAJ_Wh3TP1rWRG7F_P62c-', 'sectors': '284750', 'offset-list': [150, 15862, 33817, 51905, 71767, 88997, 102517, 118750, 137782, 154112, 158765, 175650, 182765, 202162, 217580, 239225, 248915, 268307], 'offset-count': 18}, {'id': 'lXa0xk6DI_yVSApgeIdBHkdcoYQ-', 'sectors': '282719', 'offset-list': [150, 15704, 33545, 51516, 71275, 88411, 101776, 117882, 136807, 153036, 157597, 174351, 181394, 200703, 216024, 237567, 247138, 266404], 'offset-count': 18}, {'id': 'm_iYedQMN74ix3_T31dOKf2i9f8-', 'sectors': '284562', 'offset-list': [150, 15800, 33755, 51842, 71705, 88935, 102455, 118687, 137720, 154050, 158702, 175587, 182702, 202100, 217517, 239162, 248852, 268245], 'offset-count': 18}, {'id': 'p5rco_Vix7o526Y4vyFV835jiNQ-', 'sectors': '284560', 'offset-list': [150, 15797, 33752, 51840, 71705, 88932, 102452, 118685, 137717, 154047, 158697, 175585, 182710, 202110, 217522, 239170, 248850, 268242], 'offset-count': 18}, {'id': 'qq1m2aB1_CGs09vlGGjv7hil4J8-', 'sectors': '284560', 'offset-list': [150, 15800, 33755, 51842, 71705, 88935, 102455, 118687, 137720, 154050, 158702, 175587, 182702, 202100, 217517, 239162, 248852, 268245], 'offset-count': 18}], 'disc-count': 15, 'track-list': [], 'track-count': 18}, {'position': '2', 'format': 'CD', 'disc-list': [{'id': 'AvtKRghMyE_SRGiicY5hNeiJ.k4-', 'sectors': '144343', 'offset-list': [150, 27608, 45823, 64565, 94688, 125268], 'offset-count': 6}], 'disc-count': 1, 'track-list': [], 'track-count': 6}], 'medium-count': 2, 'artist-credit-phrase': 'Moby'}, {'id': '7fa1a657-d5da-342b-a511-b5df99e5fc6b', 'title': 'Play', 'status': 'Official', 'quality': 'normal', 'packaging': 'Jewel Case', 'text-representation': {'language': 'eng', 'script': 'Latn'}, 'artist-credit': [{'artist': {'id': '8970d868-0723-483b-a75b-51088913d3d4', 'type': 'Person', 'name': 'Moby', 'sort-name': 'Moby', 'disambiguation': 'electronic musician Richard Melville Hall'}}], 'date': '1999-06', 'country': 'AU', 'release-event-list': [{'date': '1999-06', 'area': {'id': '106e0bec-b638-3b37-b731-f53d507dc00e', 'name': 'Australia', 'sort-name': 'Australia', 'iso-3166-1-code-list': ['AU']}}], 'release-event-count': 1, 'barcode': '9397603322624', 'asin': 'B0078CSP46', 'cover-art-archive': {'artwork': 'true', 'count': '1', 'front': 'true', 'back': 'false'}, 'medium-list': [{'position': '1', 'format': 'CD', 'disc-list': [{'id': '5qo5UGeX4TShw9I1jFzws9cXvPM-', 'sectors': '285693', 'offset-list': [150, 15871, 33897, 52055, 71989, 89290, 102805, 119108, 138212, 154613, 159336, 176292, 183478, 202947, 218435, 240151, 249912, 269376], 'offset-count': 18}, {'id': '6rqZnccxwrNRSrbMQpga76nxi8Y-', 'sectors': '284470', 'offset-list': [150, 15797, 33752, 51837, 71587, 88857, 102377, 118610, 137642, 153972, 158622, 175510, 182625, 202022, 217440, 239085, 248772, 268170], 'offset-count': 18}, {'id': 'ILE.c7LVuxyUINv3uf6ex0Jb3dQ-', 'sectors': '285161', 'offset-list': [150, 15902, 33879, 51986, 71879, 89151, 102651, 118893, 137953, 154318, 159015, 175904, 183082, 202526, 217983, 239661, 249367, 268768], 'offset-count': 18}, {'id': 'JA9uGF982rCaxZQelCipsxr1FXM-', 'sectors': '284630', 'offset-list': [150, 15830, 33785, 51870, 71735, 88965, 102485, 118717, 137750, 154097, 158732, 175617, 182730, 202130, 217555, 239192, 248880, 268282], 'offset-count': 18}, {'id': 'MNEZ.lH5fKXwnGgzv7c1VPhHgi4-', 'sectors': '284569', 'offset-list': [150, 15798, 33754, 51841, 71704, 88934, 102454, 118687, 137719, 154048, 158701, 175587, 182701, 202099, 217517, 239161, 248851, 268244], 'offset-count': 18}, {'id': 'PDSaNWNlRdgk3oX1gHMmFLMcn94-', 'sectors': '287148', 'offset-list': [150, 15952, 34059, 52298, 72313, 89695, 103367, 119751, 138936, 155418, 160222, 177259, 184526, 204076, 219645, 241442, 251284, 270829], 'offset-count': 18}, {'id': 'RRcrags4LSB9lwFJnGnzLryAfGQ-', 'sectors': '285061', 'offset-list': [150, 15842, 33821, 51930, 71826, 89100, 102602, 118846, 137909, 154276, 158975, 175867, 183047, 202494, 217953, 239634, 249342, 268746], 'offset-count': 18}, {'id': 'TDWrTJkwWg7flV0Z7HPDy4w1Y1M-', 'sectors': '285717', 'offset-list': [150, 15862, 33884, 52013, 71943, 89240, 102802, 119076, 138176, 154575, 159294, 176221, 183488, 203038, 218522, 240234, 249966, 269401], 'offset-count': 18}, {'id': 'Uej56Alm8YoN9wjuNKFu9ZPIhwo-', 'sectors': '284497', 'offset-list': [150, 15800, 33755, 51842, 71605, 88860, 102382, 118612, 137645, 153975, 158627, 175512, 182627, 202025, 217442, 239087, 248777, 268170], 'offset-count': 18}, {'id': 'cG.VeNwZm4a7OSkexAzZ4S2RhIU-', 'sectors': '284540', 'offset-list': [150, 15800, 33755, 51840, 71705, 88935, 102455, 118687, 137720, 154067, 158702, 175587, 182700, 202100, 217525, 239162, 248850, 268252], 'offset-count': 18}, {'id': 'fqzLHNDAJ_Wh3TP1rWRG7F_P62c-', 'sectors': '284750', 'offset-list': [150, 15862, 33817, 51905, 71767, 88997, 102517, 118750, 137782, 154112, 158765, 175650, 182765, 202162, 217580, 239225, 248915, 268307], 'offset-count': 18}, {'id': 'lXa0xk6DI_yVSApgeIdBHkdcoYQ-', 'sectors': '282719', 'offset-list': [150, 15704, 33545, 51516, 71275, 88411, 101776, 117882, 136807, 153036, 157597, 174351, 181394, 200703, 216024, 237567, 247138, 266404], 'offset-count': 18}, {'id': 'm_iYedQMN74ix3_T31dOKf2i9f8-', 'sectors': '284562', 'offset-list': [150, 15800, 33755, 51842, 71705, 88935, 102455, 118687, 137720, 154050, 158702, 175587, 182702, 202100, 217517, 239162, 248852, 268245], 'offset-count': 18}, {'id': 'p5rco_Vix7o526Y4vyFV835jiNQ-', 'sectors': '284560', 'offset-list': [150, 15797, 33752, 51840, 71705, 88932, 102452, 118685, 137717, 154047, 158697, 175585, 182710, 202110, 217522, 239170, 248850, 268242], 'offset-count': 18}, {'id': 'qq1m2aB1_CGs09vlGGjv7hil4J8-', 'sectors': '284560', 'offset-list': [150, 15800, 33755, 51842, 71705, 88935, 102455, 118687, 137720, 154050, 158702, 175587, 182702, 202100, 217517, 239162, 248852, 268245], 'offset-count': 18}], 'disc-count': 15, 'track-list': [], 'track-count': 18}], 'medium-count': 1, 'artist-credit-phrase': 'Moby'}, {'id': '447055bf-f2a4-3f4b-9124-2c7d61d845fc', 'title': 'Play', 'status': 'Official', 'quality': 'normal', 'text-representation': {'language': 'eng', 'script': 'Latn'}, 'artist-credit': [{'artist': {'id': '8970d868-0723-483b-a75b-51088913d3d4', 'type': 'Person', 'name': 'Moby', 'sort-name': 'Moby', 'disambiguation': 'electronic musician Richard Melville Hall'}}], 'date': '1999', 'country': 'ES', 'release-event-list': [{'date': '1999', 'area': {'id': '471c46a7-afc5-31c4-923c-d0444f5053a4', 'name': 'Spain', 'sort-name': 'Spain', 'iso-3166-1-code-list': ['ES']}}], 'release-event-count': 1, 'barcode': '8426946008511', 'cover-art-archive': {'artwork': 'true', 'count': '4', 'front': 'true', 'back': 'true'}, 'medium-list': [{'position': '1', 'format': 'CD', 'disc-list': [{'id': '5qo5UGeX4TShw9I1jFzws9cXvPM-', 'sectors': '285693', 'offset-list': [150, 15871, 33897, 52055, 71989, 89290, 102805, 119108, 138212, 154613, 159336, 176292, 183478, 202947, 218435, 240151, 249912, 269376], 'offset-count': 18}, {'id': '6rqZnccxwrNRSrbMQpga76nxi8Y-', 'sectors': '284470', 'offset-list': [150, 15797, 33752, 51837, 71587, 88857, 102377, 118610, 137642, 153972, 158622, 175510, 182625, 202022, 217440, 239085, 248772, 268170], 'offset-count': 18}, {'id': 'ILE.c7LVuxyUINv3uf6ex0Jb3dQ-', 'sectors': '285161', 'offset-list': [150, 15902, 33879, 51986, 71879, 89151, 102651, 118893, 137953, 154318, 159015, 175904, 183082, 202526, 217983, 239661, 249367, 268768], 'offset-count': 18}, {'id': 'JA9uGF982rCaxZQelCipsxr1FXM-', 'sectors': '284630', 'offset-list': [150, 15830, 33785, 51870, 71735, 88965, 102485, 118717, 137750, 154097, 158732, 175617, 182730, 202130, 217555, 239192, 248880, 268282], 'offset-count': 18}, {'id': 'MNEZ.lH5fKXwnGgzv7c1VPhHgi4-', 'sectors': '284569', 'offset-list': [150, 15798, 33754, 51841, 71704, 88934, 102454, 118687, 137719, 154048, 158701, 175587, 182701, 202099, 217517, 239161, 248851, 268244], 'offset-count': 18}, {'id': 'PDSaNWNlRdgk3oX1gHMmFLMcn94-', 'sectors': '287148', 'offset-list': [150, 15952, 34059, 52298, 72313, 89695, 103367, 119751, 138936, 155418, 160222, 177259, 184526, 204076, 219645, 241442, 251284, 270829], 'offset-count': 18}, {'id': 'RRcrags4LSB9lwFJnGnzLryAfGQ-', 'sectors': '285061', 'offset-list': [150, 15842, 33821, 51930, 71826, 89100, 102602, 118846, 137909, 154276, 158975, 175867, 183047, 202494, 217953, 239634, 249342, 268746], 'offset-count': 18}, {'id': 'TDWrTJkwWg7flV0Z7HPDy4w1Y1M-', 'sectors': '285717', 'offset-list': [150, 15862, 33884, 52013, 71943, 89240, 102802, 119076, 138176, 154575, 159294, 176221, 183488, 203038, 218522, 240234, 249966, 269401], 'offset-count': 18}, {'id': 'U8OSCHbKH94TmqNSa4FJIUL6wpg-', 'sectors': '284651', 'offset-list': [150, 15826, 33781, 51868, 71733, 88962, 102481, 118714, 137746, 154076, 158728, 175613, 182726, 202126, 217548, 239190, 248881, 268270], 'offset-count': 18}, {'id': 'Uej56Alm8YoN9wjuNKFu9ZPIhwo-', 'sectors': '284497', 'offset-list': [150, 15800, 33755, 51842, 71605, 88860, 102382, 118612, 137645, 153975, 158627, 175512, 182627, 202025, 217442, 239087, 248777, 268170], 'offset-count': 18}, {'id': 'cG.VeNwZm4a7OSkexAzZ4S2RhIU-', 'sectors': '284540', 'offset-list': [150, 15800, 33755, 51840, 71705, 88935, 102455, 118687, 137720, 154067, 158702, 175587, 182700, 202100, 217525, 239162, 248850, 268252], 'offset-count': 18}, {'id': 'fqzLHNDAJ_Wh3TP1rWRG7F_P62c-', 'sectors': '284750', 'offset-list': [150, 15862, 33817, 51905, 71767, 88997, 102517, 118750, 137782, 154112, 158765, 175650, 182765, 202162, 217580, 239225, 248915, 268307], 'offset-count': 18}, {'id': 'lXa0xk6DI_yVSApgeIdBHkdcoYQ-', 'sectors': '282719', 'offset-list': [150, 15704, 33545, 51516, 71275, 88411, 101776, 117882, 136807, 153036, 157597, 174351, 181394, 200703, 216024, 237567, 247138, 266404], 'offset-count': 18}, {'id': 'm_iYedQMN74ix3_T31dOKf2i9f8-', 'sectors': '284562', 'offset-list': [150, 15800, 33755, 51842, 71705, 88935, 102455, 118687, 137720, 154050, 158702, 175587, 182702, 202100, 217517, 239162, 248852, 268245], 'offset-count': 18}, {'id': 'p5rco_Vix7o526Y4vyFV835jiNQ-', 'sectors': '284560', 'offset-list': [150, 15797, 33752, 51840, 71705, 88932, 102452, 118685, 137717, 154047, 158697, 175585, 182710, 202110, 217522, 239170, 248850, 268242], 'offset-count': 18}, {'id': 'qq1m2aB1_CGs09vlGGjv7hil4J8-', 'sectors': '284560', 'offset-list': [150, 15800, 33755, 51842, 71705, 88935, 102455, 118687, 137720, 154050, 158702, 175587, 182702, 202100, 217517, 239162, 248852, 268245], 'offset-count': 18}], 'disc-count': 16, 'track-list': [], 'track-count': 18}], 'medium-count': 1, 'artist-credit-phrase': 'Moby'}, {'id': '5c57ef2f-fe72-39d7-96bb-7f5d9dc2ead4', 'title': 'Play', 'status': 'Official', 'quality': 'normal', 'text-representation': {'language': 'eng', 'script': 'Latn'}, 'artist-credit': [{'artist': {'id': '8970d868-0723-483b-a75b-51088913d3d4', 'type': 'Person', 'name': 'Moby', 'sort-name': 'Moby', 'disambiguation': 'electronic musician Richard Melville Hall'}}], 'date': '2000', 'country': 'ZA', 'release-event-list': [{'date': '2000', 'area': {'id': '50cc7852-862e-30ae-aa82-385fe7135b7f', 'name': 'South Africa', 'sort-name': 'South Africa', 'iso-3166-1-code-list': ['ZA']}}], 'release-event-count': 1, 'barcode': '6001208888432', 'asin': 'B00000J6AG', 'cover-art-archive': {'artwork': 'true', 'count': '1', 'front': 'true', 'back': 'false'}, 'medium-list': [{'position': '1', 'format': 'CD', 'disc-list': [{'id': '5qo5UGeX4TShw9I1jFzws9cXvPM-', 'sectors': '285693', 'offset-list': [150, 15871, 33897, 52055, 71989, 89290, 102805, 119108, 138212, 154613, 159336, 176292, 183478, 202947, 218435, 240151, 249912, 269376], 'offset-count': 18}, {'id': '6rqZnccxwrNRSrbMQpga76nxi8Y-', 'sectors': '284470', 'offset-list': [150, 15797, 33752, 51837, 71587, 88857, 102377, 118610, 137642, 153972, 158622, 175510, 182625, 202022, 217440, 239085, 248772, 268170], 'offset-count': 18}, {'id': 'ILE.c7LVuxyUINv3uf6ex0Jb3dQ-', 'sectors': '285161', 'offset-list': [150, 15902, 33879, 51986, 71879, 89151, 102651, 118893, 137953, 154318, 159015, 175904, 183082, 202526, 217983, 239661, 249367, 268768], 'offset-count': 18}, {'id': 'JA9uGF982rCaxZQelCipsxr1FXM-', 'sectors': '284630', 'offset-list': [150, 15830, 33785, 51870, 71735, 88965, 102485, 118717, 137750, 154097, 158732, 175617, 182730, 202130, 217555, 239192, 248880, 268282], 'offset-count': 18}, {'id': 'MNEZ.lH5fKXwnGgzv7c1VPhHgi4-', 'sectors': '284569', 'offset-list': [150, 15798, 33754, 51841, 71704, 88934, 102454, 118687, 137719, 154048, 158701, 175587, 182701, 202099, 217517, 239161, 248851, 268244], 'offset-count': 18}, {'id': 'PDSaNWNlRdgk3oX1gHMmFLMcn94-', 'sectors': '287148', 'offset-list': [150, 15952, 34059, 52298, 72313, 89695, 103367, 119751, 138936, 155418, 160222, 177259, 184526, 204076, 219645, 241442, 251284, 270829], 'offset-count': 18}, {'id': 'RRcrags4LSB9lwFJnGnzLryAfGQ-', 'sectors': '285061', 'offset-list': [150, 15842, 33821, 51930, 71826, 89100, 102602, 118846, 137909, 154276, 158975, 175867, 183047, 202494, 217953, 239634, 249342, 268746], 'offset-count': 18}, {'id': 'TDWrTJkwWg7flV0Z7HPDy4w1Y1M-', 'sectors': '285717', 'offset-list': [150, 15862, 33884, 52013, 71943, 89240, 102802, 119076, 138176, 154575, 159294, 176221, 183488, 203038, 218522, 240234, 249966, 269401], 'offset-count': 18}, {'id': 'Uej56Alm8YoN9wjuNKFu9ZPIhwo-', 'sectors': '284497', 'offset-list': [150, 15800, 33755, 51842, 71605, 88860, 102382, 118612, 137645, 153975, 158627, 175512, 182627, 202025, 217442, 239087, 248777, 268170], 'offset-count': 18}, {'id': 'cG.VeNwZm4a7OSkexAzZ4S2RhIU-', 'sectors': '284540', 'offset-list': [150, 15800, 33755, 51840, 71705, 88935, 102455, 118687, 137720, 154067, 158702, 175587, 182700, 202100, 217525, 239162, 248850, 268252], 'offset-count': 18}, {'id': 'fqzLHNDAJ_Wh3TP1rWRG7F_P62c-', 'sectors': '284750', 'offset-list': [150, 15862, 33817, 51905, 71767, 88997, 102517, 118750, 137782, 154112, 158765, 175650, 182765, 202162, 217580, 239225, 248915, 268307], 'offset-count': 18}, {'id': 'lXa0xk6DI_yVSApgeIdBHkdcoYQ-', 'sectors': '282719', 'offset-list': [150, 15704, 33545, 51516, 71275, 88411, 101776, 117882, 136807, 153036, 157597, 174351, 181394, 200703, 216024, 237567, 247138, 266404], 'offset-count': 18}, {'id': 'm_iYedQMN74ix3_T31dOKf2i9f8-', 'sectors': '284562', 'offset-list': [150, 15800, 33755, 51842, 71705, 88935, 102455, 118687, 137720, 154050, 158702, 175587, 182702, 202100, 217517, 239162, 248852, 268245], 'offset-count': 18}, {'id': 'p5rco_Vix7o526Y4vyFV835jiNQ-', 'sectors': '284560', 'offset-list': [150, 15797, 33752, 51840, 71705, 88932, 102452, 118685, 137717, 154047, 158697, 175585, 182710, 202110, 217522, 239170, 248850, 268242], 'offset-count': 18}, {'id': 'qq1m2aB1_CGs09vlGGjv7hil4J8-', 'sectors': '284560', 'offset-list': [150, 15800, 33755, 51842, 71705, 88935, 102455, 118687, 137720, 154050, 158702, 175587, 182702, 202100, 217517, 239162, 248852, 268245], 'offset-count': 18}], 'disc-count': 15, 'track-list': [], 'track-count': 18}], 'medium-count': 1, 'artist-credit-phrase': 'Moby'}, {'id': 'e554a001-1f79-432e-9667-adb192d13029', 'title': 'Play', 'status': 'Official', 'quality': 'normal', 'packaging': 'Jewel Case', 'text-representation': {'language': 'eng', 'script': 'Latn'}, 'artist-credit': [{'artist': {'id': '8970d868-0723-483b-a75b-51088913d3d4', 'type': 'Person', 'name': 'Moby', 'sort-name': 'Moby', 'disambiguation': 'electronic musician Richard Melville Hall'}}], 'date': '2000', 'country': 'US', 'release-event-list': [{'date': '2000', 'area': {'id': '489ce91b-6658-3307-9877-795b68554c98', 'name': 'United States', 'sort-name': 'United States', 'iso-3166-1-code-list': ['US']}}], 'release-event-count': 1, 'barcode': '638812704924', 'asin': 'B00000J6AG', 'cover-art-archive': {'artwork': 'true', 'count': '5', 'front': 'true', 'back': 'true'}, 'medium-list': [{'position': '1', 'format': 'CD', 'disc-list': [{'id': 'Uej56Alm8YoN9wjuNKFu9ZPIhwo-', 'sectors': '284497', 'offset-list': [150, 15800, 33755, 51842, 71605, 88860, 102382, 118612, 137645, 153975, 158627, 175512, 182627, 202025, 217442, 239087, 248777, 268170], 'offset-count': 18}], 'disc-count': 1, 'track-list': [], 'track-count': 18}], 'medium-count': 1, 'artist-credit-phrase': 'Moby'}], 'release-count': 10}}
[2023-11-27 02:44:13,431] DEBUG ARM: music_brainz.get_title discid = Uej56Alm8YoN9wjuNKFu9ZPIhwo-
[2023-11-27 02:44:13,431] DEBUG ARM: utils.database_updater crc_id=679841df-599d-402f-9f89-0d0bb6e94368:<class 'str'>
[2023-11-27 02:44:13,432] DEBUG ARM: utils.database_updater title=Moby Play:<class 'str'>
[2023-11-27 02:44:13,432] DEBUG ARM: utils.database_updater title_auto=Moby Play:<class 'str'>
[2023-11-27 02:44:13,432] DEBUG ARM: utils.database_updater video_type=Music:<class 'str'>
[2023-11-27 02:44:13,439] DEBUG ARM: utils.database_updater successfully written to the database
[2023-11-27 02:44:13,440] DEBUG ARM: job.identify_audio_cd mm_title: Moby-Play
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 186, in <module>
    drive_utils.update_drive_job(job)
  File "/opt/arm/arm/ui/settings/DriveUtils.py", line 152, in update_drive_job
    drive.new_job(job.job_id)
AttributeError: 'NoneType' object has no attribute 'new_job'
```

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by microtechno9000**
# Description
Fix for #988 - Linking to new jobs caused an error with previous job ids. Updated to try and prevent and catch the issue.
Fix for #1019 - Docker fails to start when the music folder already exists. Updated the ARM docker scripts to use 'music' not 'Music', any symbolic links to 'Music' will be removed if they exist
Web Fix - ARM web page tiles didn't work, resolved this issue now reporting "[ARM Name] - Page - ARM"
Devtools -  Removed the notification devtool feature from argparse. It uses the main ARM modules and causes code loop issues when calling any devtools feature. Code removed and will need to be resolved at a later date

Fixes #988 #1019 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration

- [x] Docker

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have tested that my fix is effective or that my feature works

# Changelog:
Multiple changes made, captured in the git file changes

# Logs
Tested docker run on multiple systems with no issues
DVD rip log
[EC_102821.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/14029759/EC_102821.log)

Docker rebuild (image remove only)
[docker_rebuild.txt](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/14029773/docker_rebuild.txt)

Docker rebuild  (image and container remove)
[docker_rebuild_clean.txt](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/14029772/docker_rebuild_clean.txt)

### CODE REVIEW

File: scripts/docker/runit/arm_user_files_setup.sh [hunk 1]
```diff
@@ -67,5 +67,5 @@ chown arm:arm /etc/abcde.conf /etc/arm/config/abcde.conf
 
 # symlink $ARM_HOME/Music to $ARM_HOME/music because the config for abcde doesn't match the docker compose docs
 # separate rm and ln commands because "ln -sf" does the wrong thing if dest is a symlink to a directory
-rm -f $ARM_HOME/music
+rm -rf $ARM_HOME/music
```
Comment (DArtagan) [inline scripts/docker/runit/arm_user_files_setup.sh:70]: Careful here.  I worry that if someone has their actual music folder mapped to this location, it will remove all their music upon launch.

Comment (microtechno9000) [reply scripts/docker/runit/arm_user_files_setup.sh:70]: agree, didn't think of that use case. Will work through another fix to mitigate that potential case.

Comment (1337-server) [reply scripts/docker/runit/arm_user_files_setup.sh:70]: I wouldn't rm/mv any of the users folders. It would be simpler to just wipe the system links by using this instead

```
# Test if abcde.conf is a hyperlink, if so remove it
if [ -h /etc/arm/config/abcde.conf ]; then
  echo "Old hyper link exists removing!"
  unlink /etc/arm/config/abcde.conf
fi
# check if abcde is in config main location - only copy if it doesnt exist
if ! [ -f /etc/arm/config/abcde.conf ]; then
  echo "abcde.conf doesnt exist"
  cp /opt/arm/setup/.abcde.conf /etc/arm/config/abcde.conf
  chown arm:arm /etc/arm/config/abcde.conf
fi
# The system link to the fake default file -not really needed but as a precaution to the -C variable being blank
if ! [ -h /etc/abcde.conf ]; then
  echo "/etc/abcde.conf link doesnt exist"
  ln -sf /etc/arm/config/abcde.conf /etc/abcde.conf
fi

```

and then change from
```
# OUTPUTDIR="$home/music/"
OUTPUTDIR="/home/arm/music/"
```
to 
```
# OUTPUTDIR="$home/Music/"
OUTPUTDIR="/home/arm/Music/"
```
Inside arm/setup/.abcde.conf

This would save on risking removing the music folder, and would put the onus on the end user on moving the old folder files to the new location. It would make it a breaking change, but its safer than wiping the users old rips.

Comment (microtechno9000) [reply scripts/docker/runit/arm_user_files_setup.sh:70]: Looks good, will add those checks

I have made changes to the docker and other setup scripts to only use music not Music, havent pushed that change yet. Will add your changes and check it all works

File: devtools/armnotify.py [hunk 2]
```diff
@@ -4,23 +4,25 @@
...
+#     """
+#     Run a notification
+#         INPUT: none
+#         OUTPUT: none
+#     """
+#     try:
+#         job = Job("/dev/null")
+#         utils.notify(job, "ARM notification", "This is a notification by the ARM-Notification Test!")
+#     except Exception as error:
+#         log.error(f"ARM Notify failed to run - {error}")
```
Comment (shitwolfymakes) [inline devtools/armnotify.py:28]: Go ahead and strip out the commented out code You can always refer to the git history if you don't want to rewrite it in the future.

File: devtools/armnotify.py [hunk 3]
```diff
@@ -4,23 +4,25 @@
...
-import log
-import sys
-sys.path.insert(0, '/opt/arm')
-from arm.ripper import utils        # noqa E402
-from arm.models.job import Job   # noqa E402
+# import log
+# import sys
+# sys.path.insert(0, '/opt/arm')
+# from arm.ripper import utils        # noqa E402
+# from arm.models.job import Job   # noqa E402
```
Comment (shitwolfymakes) [inline devtools/armnotify.py:15]: Go ahead and strip out the commented out code You can always refer to the git history if you don't want to rewrite it in the future.

**Review by shitwolfymakes — CHANGES_REQUESTED** [review]

**Comment by microtechno9000** [comment]
Accidently deleted the branch, removing the PR, PR still good and review requested

**Review by shitwolfymakes — APPROVED** [review]
Container built with zero issues, test run was successful
